"""
Database models for the solver app.
Two models: Problem and Solution.
"""

from django.db import models


class Problem(models.Model):
    """
    Stores the LeetCode problem fetched by Selenium.
    """
    problem_number = models.IntegerField(unique=True)   # e.g., 1 for Two Sum
    title = models.CharField(max_length=300)             # e.g., "Two Sum"
    description = models.TextField()                     # Full problem text
    created_at = models.DateTimeField(auto_now_add=True) # Auto timestamp

    def __str__(self):
        return f"#{self.problem_number} - {self.title}"


class Solution(models.Model):
    """
    Stores the GPT-generated solution and submission result for a problem.
    """

    # Status choices for submission result
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('wrong_answer', 'Wrong Answer'),
        ('tle', 'Time Limit Exceeded'),
        ('error', 'Error'),
    ]

    # Link to the Problem model
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, related_name='solutions')

    generated_code = models.TextField()     # Python code generated by GPT
    submission_status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='pending'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Solution for #{self.problem.problem_number} - {self.submission_status}"
